# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

if [ -f ~/.bashrc-system-specific ]; then
    . ~/.bashrc-system-specific
fi


# use vi mode
set -o vi

# load svn-color for pretty svn!
# . ~/bin/svn-color/svn-color.sh
# ensure it will work through less
export SVN_COLOR=always

# User specific aliases and functions
alias ls="ls --color=auto"
alias ll="ls -lh"

alias vi=vim
alias less="less -R" # always display colors
alias s=sudo
alias open=xdg-open
alias start=xdg-open

# Start feh in fullscreen, with filenames turned on, and captions
alias feh="feh -F -d --caption-path captions"

# pacman aliases
alias p="sudo pacman"
alias pacs="sudo pacman -Ss"
alias paci="sudo pacman -S"
alias aurs="yaourt -Ss"
alias auri="yaourt -S"

alias sys="sudo systemctl"


alias pg='ps -ef | grep'

alias music="ncmpcpp"


# location variables

export rclua=$HOME/.config/awesome/rc.lua

export SVN_EDITOR=gvim

export JAVA_HOME=/opt/jdk1.7.0_45
export ORACLE_HOME=/usr/lib/oracle/11.2/client64
export TNS_ADMIN=$ORACLE_HOME/network/admin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ORACLE_HOME/lib

# paths
DOTFILESBIN=~/.dotfiles/bin
DOTFILESBINS=~/.dotfiles/system-specific-bin
POWERLINEP=~/.dotfiles/submodules/powerline/scripts
GEMSBIN=~/.gem/ruby/2.0.0/bin

MPLAYER_PATH=/opt/mplayer2/bin

LOCALPATH=$DOTFILESBIN:$DOTFILESBINS:$MPLAYER_PATH:$POWERLINEP:$GEMSBIN


export PATH=$LOCALPATH:$JAVA_HOME/bin:$ORACLE_HOME/bin:$PATH



