# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

if [ -f ~/.bashrc-system-specific ]; then
    . ~/.bashrc-system-specific
fi


# a simple command to set xterm/tmux window titles to the pwd
. /usr/share/git/completion/git-prompt.sh
export PROMPT_COMMAND='printf "\033_%s%s\033\\" "${PWD/#$HOME/\~}" "$(__git_ps1 " (%s)")"'

# use vi mode
set -o vi

# load svn-color for pretty svn!
# . ~/bin/svn-color/svn-color.sh
# ensure it will work through less
export SVN_COLOR=always
function svnlog {
    svn log | less
}

# User specific aliases and functions
alias ls="ls --color=auto"
alias ll="ls -lh"
alias llt="ls -lht | head"

alias vi=nvim
alias less="less -R" # always display colors
alias s=sudo
alias open=xdg-open
alias start=xdg-open

# Start feh in fullscreen, with filenames turned on, and captions
alias feh="feh -F -d --caption-path captions"

# pacman aliases
alias p="sudo pacman"
alias pacs="sudo pacman -Ss"
alias paci="sudo pacman -S"
alias aurs="yaourt -Ss"
alias auri="yaourt -S"

alias sys="sudo systemctl"

alias grep='grep --color=always -n'

alias pg='ps -ef | grep'

alias music="ncmpcpp"

alias ipy='ipython2 --no-confirm-exit'
alias py='ptpython --vi'

alias t='tmux'

alias dict='sdcv -n'
alias define='sdcv -n'

# location variables

export rclua=$HOME/.config/awesome/rc.lua

export SVN_EDITOR=nvim

export JAVA_HOME=/opt/jdk1.7.0_65
# ensure java always uses pretty fonts, instead of terrible ones..
export _JAVA_OPTIONS="-Dawt.useSystemAAFontSettings=gasp"

# paths
DOTFILESBIN=~/.dotfiles/bin
DOTFILESBINS=~/.dotfiles/system-specific-bin
POWERLINEP=~/.dotfiles/submodules/powerline/scripts
GEMSBIN=~/.gem/ruby/2.1.0/bin

MPLAYER_PATH=/opt/mplayer2/bin

MISCBIN=/home/quasar/git/misc_scripts

LOCALPATH=$DOTFILESBIN:$DOTFILESBINS:$MPLAYER_PATH:$POWERLINEP:$GEMSBIN
AOC_PYTHON=/home/quasar/.local/lib/python2.7/site-packages/aoc

export GOPATH=$HOME/go
GNUPRICING=~/gnu-pricing/bin

export PATH=$GNUPRICING:$LOCALPATH:$JAVA_HOME/bin:$PATH:$GOPATH/bin:$MISCBIN

export EDITOR=vim
export aoc=/home/quasar/.local/lib/python2.7/site-packages/aoc
export aoc3=/home/quasar/.local/lib/python3.4/site-packages/aoc

field=
record=

# fix for Sakura and other VTE-based terminals,
# which insist on setting TERM to xterm
if [ -n "$VTE_VERSION" ]; then
    export TERM=xterm-256color
fi

# neovim env var options
. ~/.nvim/env.sh

# Remind myself of open tasks
task

